/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <unistd.h>
#include <netinet/ip_icmp.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <android/log.h>
#include <signal.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <netinet/ip.h>
#include <netdb.h>
#include<android/log.h>
/* Header for class com_demo_gourdboy_netisoklinux_NativeMethod */

#ifndef _Included_com_demo_gourdboy_netisoklinux_NativeMethod
#define _Included_com_demo_gourdboy_netisoklinux_NativeMethod
#ifndef DEBUG
#define DEBUG 1
#endif
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_gourdboy_netisoklinux_NativeMethod
 * Method:    isNetOk
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_demo_gourdboy_netisoklinux_NativeMethod_isNetOk
  (JNIEnv *, jobject, jstring);


JNIEXPORT void JNICALL Java_com_demo_gourdboy_netisoklinux_NativeMethod_netOkInit
(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_demo_gourdboy_netisoklinux_NativeMethod_setIP
(JNIEnv *, jobject,jstring);
JNIEXPORT void JNICALL Java_com_demo_gourdboy_netisoklinux_NativeMethod_netOkThreadStart
(JNIEnv *, jobject);
JNIEXPORT void JNICALL Java_com_demo_gourdboy_netisoklinux_NativeMethod_netOkThreadStop
(JNIEnv *, jobject);
static void* thread_isNetOk_exec();
#ifdef __cplusplus
}
#endif
#endif
